
[King_PrincessTowers]
    [[King_PrincessTowers.Objects]]
    Data = "KingTower"
    x = 18
    y = 6
    [[King_PrincessTowers.Objects]]
    Data = "PrincessTower"
    x = 7
    y = 13

    [[King_PrincessTowers.Objects]]
    Data = "PrincessTower"
    x = 29
    y = 13

[King_PrincessTowers2v2]
    [[King_PrincessTowers2v2.Objects]]
    Data = "KingTower"
    x = 14
    y = 6
    [[King_PrincessTowers2v2.Objects]]
    Data = "PrincessTower"
    x = 7
    y = 13

[Heist]
    [[Heist.Objects]]
    Data = "HeistStorage"
    x = 18
    y = 6

[King_CannonTowers]
    [[King_CannonTowers.Objects]]
    Data = "KingTower"
    x = 18
    y = 6
    [[King_CannonTowers.Objects]]
    Data = "Cannoneer"
    x = 7
    y = 13

    [[King_CannonTowers.Objects]]
    Data = "Cannoneer"
    x = 29
    y = 13

[King_CannonTowers2v2]
    [[King_CannonTowers2v2.Objects]]
    Data = "KingTower"
    x = 14
    y = 6
    [[King_CannonTowers2v2.Objects]]
    Data = "Cannoneer"
    x = 7
    y = 13

[King_KnifeTowers]
    [[King_KnifeTowers.Objects]]
    Data = "KingTower"
    x = 18
    y = 6
    [[King_KnifeTowers.Objects]]
    Data = "DaggerDuchess"
    x = 7
    y = 13

    [[King_KnifeTowers.Objects]]
    Data = "DaggerDuchess"
    x = 29
    y = 13

[King_KnifeTowers2v2]
    [[King_KnifeTowers2v2.Objects]]
    Data = "KingTower"
    x = 14
    y = 6
    [[King_KnifeTowers2v2.Objects]]
    Data = "DaggerDuchess"
    x = 7
    y = 13

[BattleGround_Spawnblocker]
    [[BattleGround_Spawnblocker.Objects]]
    Data = "BattleGround_Spawnblocker"
    x = 18
    y = 6
    
[GoblinQueen_SpawnAbility]
    [[GoblinQueen_SpawnAbility.Objects]]
    Data = "GoblinQueenTower"
    x = 18
    y = 6
    [[GoblinQueen_SpawnAbility.Objects]]
    Data = "GoblinQueenSecondaryTower"
    x = 7
    y = 13
    [[GoblinQueen_SpawnAbility.Objects]]
    Data = "GoblinQueenSecondaryTower"
    x = 29
    y = 13

[GoblinQueen_SpawnAbility2v2]
    [[GoblinQueen_SpawnAbility2v2.Objects]]
    Data = "GoblinQueenTower"
    x = 14
    y = 6
    [[GoblinQueen_SpawnAbility2v2.Objects]]
    Data = "GoblinQueenSecondaryTower"
    x = 7
    y = 13

[Event_GoblinBush_Spawner]
    [[Event_GoblinBush_Spawner.Objects]]
    Data = "Event_BushSpawner"
    x = 18
    y = 6

[Event_SpawnMelee]
    [[Event_SpawnMelee.Objects]]
    Data = "KingTower_SpawnMelee"
    x = 18
    y = 6
    [[Event_SpawnMelee.Objects]]
    Data = "PrincessTower"
    x = 7
    y = 13

    [[Event_SpawnMelee.Objects]]
    Data = "PrincessTower"
    x = 29
    y = 13


[202410_Event_Spooky_Chess]
    [[202410_Event_Spooky_Chess.Objects]]
    Data = "KingTower_SpookyChess"
    x = 21
    y = 4

    [[202410_Event_Spooky_Chess.Objects]]
    Data = "PrincessTower_SpookyChess"
    x = 15
    y = 4

    [[202410_Event_Spooky_Chess.Objects]]
    Data = "AxeManTower_SpookyChess"
    x = 10
    y = 4

    [[202410_Event_Spooky_Chess.Objects]]
    Data = "AxeManTower_SpookyChess"
    x = 26
    y = 4

    [[202410_Event_Spooky_Chess.Objects]]
    Data = "DarkPrinceTower_SpookyChess"
    x = 6
    y = 4

    [[202410_Event_Spooky_Chess.Objects]]
    Data = "DarkPrinceTower_SpookyChess"
    x = 30
    y = 4

    [[202410_Event_Spooky_Chess.Objects]]
    Data = "BombTower_chess"
    x = 2
    y = 4

    [[202410_Event_Spooky_Chess.Objects]]
    Data = "BombTower_chess"
    x = 34
    y = 4

[Event_Gift_Delivery]
    [[Event_Gift_Delivery.Objects]]
    Data = "KingTower_Gift_Delivery"
    x = 18
    y = 6
    
    [[Event_Gift_Delivery.Objects]]
    Data = "PrincessTower"
    x = 7
    y = 13

    [[Event_Gift_Delivery.Objects]]
    Data = "PrincessTower"
    x = 29
    y = 13
[AllRandom_SpawnGroup]
    [[AllRandom_SpawnGroup.Objects]]
    Data = "KingTower_AllRandom"
    x = 15
    y = 3

[King_ChefTowers]
    [[King_ChefTowers.Objects]]
    Data = "ChefTowerKing"
    x = 18
    y = 6
    [[King_ChefTowers.Objects]]
    Data = "ChefTower"
    x = 7
    y = 13

    [[King_ChefTowers.Objects]]
    Data = "ChefTower"
    x = 29
    y = 13

[King_ChefTowers2v2]
    [[King_ChefTowers2v2.Objects]]
    Data = "ChefTowerKing"
    x = 14
    y = 6
    [[King_ChefTowers2v2.Objects]]
    Data = "ChefTower"
    x = 7
    y = 13
